/**
 *
 * @author John Erice / Immer Gonzalez
 * Proyecto modulo 2 de Java
 * @version 1.0
 */
package views;

/**
 *
 * Importacion de Librerias y paquetes
 * 
 * 
 */


import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import models.DataAccess;
import java.util.Date;
import models.validar_usuario;
import structures.I_ValidarUsuario;

public class Acceso extends javax.swing.JFrame {
    
 /**
 *
 * Declaracion de Variables
 * 
 */    
    public static String nombre_acceso=java.util.ResourceBundle.getBundle("views/Bundle").getString("");
    public static String nro_usuario=java.util.ResourceBundle.getBundle("views/Bundle").getString("");
    public static String fechag=java.util.ResourceBundle.getBundle("views/Bundle").getString("");
    
    public Acceso() {
       initComponents();
       this.setLocationRelativeTo(null);
       txtfnrotarjeta.setText(null);
       txtfclave.setText(null);
       txtfnrotarjeta.requestFocus();
    }
    
 /**
 * 
 * Permite obtener la fecha del Sistema
 * 
 */
    public void obtener_fecha_sistema(String fecha3) 
    {        
        initComponents();
        this.setLocationRelativeTo(null);
        Date fecha = new Date();
        SimpleDateFormat formatofecha=new SimpleDateFormat(java.util.ResourceBundle.getBundle("views/Bundle").getString("DD/MM/YYYY"));
        //
        fechag = formatofecha.format(fecha);
    }
 
 /**
 * 
 * Permite validar el usuario para ingresar al Sistema
 * 
 */
    
  public void validar_usuario(String nro_tarjeta,String clav){
        String sql; 
        sql = java.util.ResourceBundle.getBundle("views/Bundle").getString("SELECT * FROM BDBANCO.USUARIO WHERE NRO_TARJETA='")+nro_tarjeta+java.util.ResourceBundle.getBundle("views/Bundle").getString("' && CLAVE_USUARIO='")+clav+java.util.ResourceBundle.getBundle("views/Bundle").getString("'");
          String result2=java.util.ResourceBundle.getBundle("views/Bundle").getString("");
          Boolean result1;
            try {
                Statement ste = con.createStatement();
                ResultSet rs = ste.executeQuery(sql);            
                while(rs.next()) {
                   result2 = (rs.getString("nro_tarjeta"));         
                    nombre_acceso = (rs.getString("nombre_usuario"));
                    nro_usuario = (rs.getString("id_usuario"));
                    // Se cierra la Ventana de Acceso
                    this.setVisible(false);
                    //Se Desplega la pantalla de Bienvenida
                        Bienvenida entrada = new Bienvenida();
                entrada.setVisible(true);
                entrada.pack();
                }
        } catch (SQLException ex) {
            System.out.println(java.util.ResourceBundle.getBundle("views/Bundle").getString("NO EXUSTE EN LA BD"));
            System.out.println(ex.getMessage());}               
 
} 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        jDialog1 = new javax.swing.JDialog();
        jFrame1 = new javax.swing.JFrame();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        lblusuario = new javax.swing.JLabel();
        lblclave = new javax.swing.JLabel();
        txtusuario = new javax.swing.JLabel();
        txtclave = new javax.swing.JLabel();
        btnaceptar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        txtfnrotarjeta = new javax.swing.JTextField();
        txtfclave = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnsalir = new javax.swing.JToggleButton();
        jtxtfecha = new javax.swing.JLabel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("views/Bundle"); // NOI18N
        jMenu1.setText(bundle.getString("JMENU1")); // NOI18N

        jMenu2.setText(bundle.getString("JMENU2")); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText(bundle.getString("CAJERO AUTOMATICO")); // NOI18N

        lblusuario.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblusuario.setText(bundle.getString("NRO. DE TARJETA:")); // NOI18N

        lblclave.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblclave.setText(bundle.getString("CLAVE:")); // NOI18N

        txtusuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtclave.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btnaceptar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnaceptar.setIcon(new javax.swing.ImageIcon("C:\\Users\\john\\Downloads\\aceptar-icono-6494-32.png")); // NOI18N
        btnaceptar.setText(bundle.getString("ACEPTAR")); // NOI18N
        btnaceptar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnaceptar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnaceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnaceptarMouseClicked(evt);
            }
        });
        btnaceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaceptarActionPerformed(evt);
            }
        });

        btncancelar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btncancelar.setIcon(new javax.swing.ImageIcon("C:\\Users\\john\\Downloads\\cancelar-icono-4839-32.png")); // NOI18N
        btncancelar.setText(bundle.getString("CANCELAR")); // NOI18N
        btncancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btncancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });

        txtfnrotarjeta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtfnrotarjetaKeyTyped(evt);
            }
        });

        txtfclave.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtfclaveKeyTyped(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\john\\Downloads\\llave-icono-9419-48.png")); // NOI18N

        jLabel4.setText(bundle.getString("JLABEL4")); // NOI18N

        btnsalir.setIcon(new javax.swing.ImageIcon("C:\\Users\\john\\Downloads\\liberacion-de-la-puerta-icono-7259-16.png")); // NOI18N
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblclave)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblusuario)
                                        .addComponent(btnaceptar))
                                    .addGap(35, 35, 35)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtfnrotarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtfclave, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btncancelar))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(284, 284, 284))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jtxtfecha)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnsalir))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtclave, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(282, 282, 282))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(jLabel1)
                                .addGap(35, 35, 35))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)
                                .addGap(26, 26, 26)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblusuario)
                            .addComponent(txtfnrotarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtusuario)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblclave)
                                .addComponent(txtfclave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(16, 16, 16)
                        .addComponent(txtclave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnaceptar)
                            .addComponent(btncancelar))
                        .addGap(46, 46, 46)
                        .addComponent(btnsalir))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtfecha, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
  
    private void btnaceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnaceptarMouseClicked
       
    }//GEN-LAST:event_btnaceptarMouseClicked

    private void btnaceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaceptarActionPerformed
        String nro_tarjeta = txtfnrotarjeta.getText();
        String clav = txtfclave.getText();
          String texto=txtfnrotarjeta.getText();
          Integer Variable3=2;
          Integer Variable1=2;
        texto=texto.replaceAll(java.util.ResourceBundle.getBundle("views/Bundle").getString(" "), java.util.ResourceBundle.getBundle("views/Bundle").getString(""));
        if(texto.length()==0){
          Variable3=2;
          Variable1=2;
          txtfnrotarjeta.setText(null);
          txtfclave.setText(null);
      
 }
        else
        {
         Variable3=1;
              }
         String texto1=txtfclave.getText();
         texto1=texto1.replaceAll(java.util.ResourceBundle.getBundle("views/Bundle").getString(" "), java.util.ResourceBundle.getBundle("views/Bundle").getString(""));
          if(texto1.length()==0){
          Variable3=2;
          Variable1=2;
           txtfnrotarjeta.setText(null);
            txtfclave.setText(null);
          }
        else
        {
         Variable1=1;
        }
          if ( (Variable3 == 1) && (Variable1==1 )){
            obtener_fecha_sistema(fechag);
            validar_usuario(nro_tarjeta,clav);} 
          else{
            txtfnrotarjeta.setText(null);
            txtfclave.setText(null);
            txtfnrotarjeta.requestFocus();
            JOptionPane.showMessageDialog(null,java.util.ResourceBundle.getBundle("views/Bundle").getString("INCORPORA EL NRO DE TARJETA Y CLAVE VALIDO,PARA PODER INGRESAR AL SISTEMA!!"));
          }
          Variable3=2;
          Variable1=2;                       
          txtfnrotarjeta.setText(null);
            txtfclave.setText(null);
       txtfnrotarjeta.requestFocus();
    }//GEN-LAST:event_btnaceptarActionPerformed
     
    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnsalirActionPerformed

    private void txtfnrotarjetaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfnrotarjetaKeyTyped
        // TODO add your handling code here:
       char cc = evt.getKeyChar();
        if(cc<'0'|| cc>'9') evt.consume();
    }//GEN-LAST:event_txtfnrotarjetaKeyTyped

    private void txtfclaveKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfclaveKeyTyped
        // TODO add your handling code here:
       char cc = evt.getKeyChar();
        if(cc<'0'|| cc>'9') evt.consume();
    }//GEN-LAST:event_txtfclaveKeyTyped

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        txtfnrotarjeta.setText(null);
        txtfclave.setText(null);
        txtfnrotarjeta.requestFocus();
  
    }//GEN-LAST:event_btncancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        // Abre la conexion a la Base de Datos.
        DataAccess a;
        a=new DataAccess();
        Connection reg = a.connectToDB();
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if (java.util.ResourceBundle.getBundle("views/Bundle").getString("NIMBUS").equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Acceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Acceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Acceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Acceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Acceso().setVisible(true);
             }
            
        });
     }

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaceptar;
    private javax.swing.JButton btncancelar;
    private javax.swing.JToggleButton btnsalir;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JLabel jtxtfecha;
    private javax.swing.JLabel lblclave;
    private javax.swing.JLabel lblusuario;
    private javax.swing.JLabel txtclave;
    private javax.swing.JTextField txtfclave;
    private javax.swing.JTextField txtfnrotarjeta;
    private javax.swing.JLabel txtusuario;
    // End of variables declaration//GEN-END:variables

// Se efectua la instancia de Conexion a la Bade de Datos
  DataAccess cn = new DataAccess();
  Connection con = cn.connectToDB();
 
}