/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.ProcessController;
import javax.swing.JOptionPane;
import models.FileControl;
import models.Moves;
import models.User;

/**
 *
 * @author shaka
 */
public class MainFrame extends javax.swing.JFrame {
    int control = 0;

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTarjeta = new javax.swing.JLabel();
        txtTarjeta = new javax.swing.JTextField();
        lblClave = new javax.swing.JLabel();
        passClave = new javax.swing.JPasswordField();
        btnInsUsuarios = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnSaldo = new javax.swing.JButton();
        btnDeposito = new javax.swing.JButton();
        btnRetiro = new javax.swing.JButton();
        btnCambiar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lblSaldo = new javax.swing.JLabel();
        txtSaldo = new javax.swing.JTextField();
        lblImporte = new javax.swing.JLabel();
        txtImporte = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lblBanco = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lblBienvenida = new javax.swing.JLabel();
        lblCliente = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cajero Automático");

        lblTarjeta.setText("Tarjeta");
        jPanel1.add(lblTarjeta);

        txtTarjeta.setColumns(10);
        jPanel1.add(txtTarjeta);

        lblClave.setText("Clave");
        jPanel1.add(lblClave);

        passClave.setColumns(10);
        passClave.setToolTipText("");
        jPanel1.add(passClave);

        btnInsUsuarios.setText("Insertar Usuarios");
        btnInsUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsUsuariosActionPerformed(evt);
            }
        });
        jPanel1.add(btnInsUsuarios);

        btnSaldo.setText("Consulta de Saldo");
        btnSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaldoActionPerformed(evt);
            }
        });
        jPanel2.add(btnSaldo);

        btnDeposito.setText("Depósito");
        btnDeposito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepositoActionPerformed(evt);
            }
        });
        jPanel2.add(btnDeposito);

        btnRetiro.setText("Retiro");
        btnRetiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetiroActionPerformed(evt);
            }
        });
        jPanel2.add(btnRetiro);

        btnCambiar.setText("Cambiar Clave");
        jPanel2.add(btnCambiar);

        lblSaldo.setText("Saldo:");
        jPanel3.add(lblSaldo);

        txtSaldo.setColumns(10);
        jPanel3.add(txtSaldo);

        lblImporte.setText("Importe:");
        jPanel3.add(lblImporte);

        txtImporte.setColumns(10);
        jPanel3.add(txtImporte);

        lblBanco.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblBanco.setForeground(new java.awt.Color(0, 0, 102));
        lblBanco.setText("BANDURO");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Aquí su dinero está Seguro");

        lblBienvenida.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblBienvenida.setForeground(new java.awt.Color(0, 0, 102));
        lblBienvenida.setText("Buen Día");

        lblCliente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCliente.setForeground(new java.awt.Color(0, 0, 102));
        lblCliente.setText("Cliente");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(159, 159, 159)
                                .addComponent(lblBanco))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(lblBienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblBanco, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBienvenida)
                    .addComponent(lblCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsUsuariosActionPerformed
            // Insertar registros de usuarios
        
        String rutaUser = "./usuarios.txt";
        
        User usuario = new User();
        int insertar = 0;
        
        usuario.setTarjeta(txtTarjeta.getText());
        usuario.setClave(passClave.getText());  
        usuario.setSaldo(txtSaldo.getText());   
        
        if ((txtTarjeta.getText().isEmpty()) || (passClave.getText().isEmpty()) ||
           (txtSaldo.getText().isEmpty())) {
                JOptionPane.showMessageDialog(btnInsUsuarios, "Recuerde completar los campos: Tarjeta, clave y saldo.");
                insertar = 1;
            }  
        System.out.println(insertar);
        
        if (insertar < 1) {
            String contenido = (usuario.getTarjeta() + ';' 
                  + usuario.getClave() + ';' + usuario.getSaldo()) + ';';
            if (control > 0) {
                FileControl.anexar(rutaUser, contenido);  
                txtTarjeta.setText("");
                passClave.setText("");
                txtSaldo.setText("");
                control ++;
                if (control > 10) {
                    JOptionPane.showMessageDialog(btnInsUsuarios, "Llegó al límite de registros permintidos.");
                } 
            } else {
                FileControl.crear(rutaUser);
                String encabezado = ("TARJETA" + ';' + "CLAVE" + ';' + "SALDO" + ';');              
                FileControl.escribir(rutaUser, encabezado);
                FileControl.anexar(rutaUser, contenido);
                txtTarjeta.setText("");
                passClave.setText("");
                txtSaldo.setText("");
                control ++;                    
                }
            }        
    }//GEN-LAST:event_btnInsUsuariosActionPerformed

    private void btnSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSaldoActionPerformed

    private void btnDepositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepositoActionPerformed
        // Insertar movimientos de depósitos
        
        String rutaUser = "./movimientos.txt";
        
        Moves movimiento = new Moves();
        int insertar = 0;
        
        movimiento.setTarjeta(txtTarjeta.getText());
        movimiento.setImporte(txtImporte.getText());  
        movimiento.setTipo('I');        
        
        if ((txtTarjeta.getText().isEmpty()) || 
           (txtImporte.getText().isEmpty())) {
                JOptionPane.showMessageDialog(btnInsUsuarios, "Recuerde completar los campos: Tarjeta e importe.");
                insertar = 1;
            }
        
        if (insertar < 1) {
            String contenido = (movimiento.getTarjeta() + ';' 
                   + movimiento.getImporte() + ';' + movimiento.getTipo()) + ';';        
            if (control > 0) {
                FileControl.anexar(rutaUser, contenido);  
                txtTarjeta.setText("");
                txtImporte.setText("");
                control ++;
            } else {
                FileControl.crear(rutaUser);
                String encabezado = ("TARJETA" + ';' + "IMPORTE" + ';' + "TIPO" + ';');              
                FileControl.escribir(rutaUser, encabezado);
                FileControl.anexar(rutaUser, contenido);
                txtTarjeta.setText("");
                txtImporte.setText("");
                control ++;                    
            }
        }
    }//GEN-LAST:event_btnDepositoActionPerformed

    private void btnRetiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetiroActionPerformed
        
        String rutaUser = "./movimientos.txt";
        
        Moves movimiento = new Moves();
        int insertar = 0;
        
        movimiento.setTarjeta(txtTarjeta.getText());
        movimiento.setImporte(txtImporte.getText());  
        movimiento.setTipo('E');        
        
        if ((txtTarjeta.getText().isEmpty()) || 
           (txtImporte.getText().isEmpty())) {
                JOptionPane.showMessageDialog(btnInsUsuarios, "Recuerde completar los campos: Tarjeta e importe.");
                insertar = 1;
            }
        if (insertar < 1) {
            String contenido = (movimiento.getTarjeta() + ';' 
                   + movimiento.getImporte() + ';' + movimiento.getTipo()) + ';';        
            if (control > 0) {
                FileControl.anexar(rutaUser, contenido);  
                txtTarjeta.setText("");
                txtImporte.setText("");
                control ++;
            } else {
                FileControl.crear(rutaUser);
                String encabezado = ("TARJETA" + ';' + "IMPORTE" + ';' + "TIPO" + ';');              
                FileControl.escribir(rutaUser, encabezado);
                FileControl.anexar(rutaUser, contenido);
                txtTarjeta.setText("");
                txtImporte.setText("");
                control ++;                    
            }
        }
    }//GEN-LAST:event_btnRetiroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCambiar;
    private javax.swing.JButton btnDeposito;
    private javax.swing.JButton btnInsUsuarios;
    private javax.swing.JButton btnRetiro;
    private javax.swing.JButton btnSaldo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblBanco;
    private javax.swing.JLabel lblBienvenida;
    private javax.swing.JLabel lblClave;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblImporte;
    private javax.swing.JLabel lblSaldo;
    private javax.swing.JLabel lblTarjeta;
    private javax.swing.JPasswordField passClave;
    private javax.swing.JTextField txtImporte;
    private javax.swing.JTextField txtSaldo;
    private javax.swing.JTextField txtTarjeta;
    // End of variables declaration//GEN-END:variables
}
